# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-XmlMatch
version:      1.0004
version_from: lib/Text/XmlMatch.pm
installdirs:  site
requires:
    Test::Simple:                  0.44
    XML::Simple:                   2.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
